/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authIndexRouteImport } from './routes/(auth)/index'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as appDashboardRouteImport } from './routes/(app)/dashboard'
import { Route as appDashboardHomeIndexRouteImport } from './routes/(app)/dashboard/home/index'
import { Route as appDashboardCompaniesIndexRouteImport } from './routes/(app)/dashboard/companies/index'
import { Route as appDashboardProjectsProjectIdIndexRouteImport } from './routes/(app)/dashboard/projects/$projectId/index'
import { Route as appDashboardCompanyIdProjectsIndexRouteImport } from './routes/(app)/dashboard/$companyId/projects/index'
import { Route as appDashboardProjectsProjectIdTicketsIndexRouteImport } from './routes/(app)/dashboard/projects/$projectId/tickets/index'
import { Route as appDashboardProjectsProjectIdTicketsTicketIdIndexRouteImport } from './routes/(app)/dashboard/projects/$projectId/tickets/$ticketId/index'
import { Route as appDashboardProjectsProjectIdStoriesStoryIdIndexRouteImport } from './routes/(app)/dashboard/projects/$projectId/stories/$storyId/index'

const authIndexRoute = authIndexRouteImport.update({
  id: '/(auth)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const appDashboardRoute = appDashboardRouteImport.update({
  id: '/(app)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const appDashboardHomeIndexRoute = appDashboardHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => appDashboardRoute,
} as any)
const appDashboardCompaniesIndexRoute =
  appDashboardCompaniesIndexRouteImport.update({
    id: '/companies/',
    path: '/companies/',
    getParentRoute: () => appDashboardRoute,
  } as any)
const appDashboardProjectsProjectIdIndexRoute =
  appDashboardProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => appDashboardRoute,
  } as any)
const appDashboardCompanyIdProjectsIndexRoute =
  appDashboardCompanyIdProjectsIndexRouteImport.update({
    id: '/$companyId/projects/',
    path: '/$companyId/projects/',
    getParentRoute: () => appDashboardRoute,
  } as any)
const appDashboardProjectsProjectIdTicketsIndexRoute =
  appDashboardProjectsProjectIdTicketsIndexRouteImport.update({
    id: '/projects/$projectId/tickets/',
    path: '/projects/$projectId/tickets/',
    getParentRoute: () => appDashboardRoute,
  } as any)
const appDashboardProjectsProjectIdTicketsTicketIdIndexRoute =
  appDashboardProjectsProjectIdTicketsTicketIdIndexRouteImport.update({
    id: '/projects/$projectId/tickets/$ticketId/',
    path: '/projects/$projectId/tickets/$ticketId/',
    getParentRoute: () => appDashboardRoute,
  } as any)
const appDashboardProjectsProjectIdStoriesStoryIdIndexRoute =
  appDashboardProjectsProjectIdStoriesStoryIdIndexRouteImport.update({
    id: '/projects/$projectId/stories/$storyId/',
    path: '/projects/$projectId/stories/$storyId/',
    getParentRoute: () => appDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof appDashboardRouteWithChildren
  '/signup': typeof authSignupRoute
  '/': typeof authIndexRoute
  '/dashboard/companies': typeof appDashboardCompaniesIndexRoute
  '/dashboard/home': typeof appDashboardHomeIndexRoute
  '/dashboard/$companyId/projects': typeof appDashboardCompanyIdProjectsIndexRoute
  '/dashboard/projects/$projectId': typeof appDashboardProjectsProjectIdIndexRoute
  '/dashboard/projects/$projectId/tickets': typeof appDashboardProjectsProjectIdTicketsIndexRoute
  '/dashboard/projects/$projectId/stories/$storyId': typeof appDashboardProjectsProjectIdStoriesStoryIdIndexRoute
  '/dashboard/projects/$projectId/tickets/$ticketId': typeof appDashboardProjectsProjectIdTicketsTicketIdIndexRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof appDashboardRouteWithChildren
  '/signup': typeof authSignupRoute
  '/': typeof authIndexRoute
  '/dashboard/companies': typeof appDashboardCompaniesIndexRoute
  '/dashboard/home': typeof appDashboardHomeIndexRoute
  '/dashboard/$companyId/projects': typeof appDashboardCompanyIdProjectsIndexRoute
  '/dashboard/projects/$projectId': typeof appDashboardProjectsProjectIdIndexRoute
  '/dashboard/projects/$projectId/tickets': typeof appDashboardProjectsProjectIdTicketsIndexRoute
  '/dashboard/projects/$projectId/stories/$storyId': typeof appDashboardProjectsProjectIdStoriesStoryIdIndexRoute
  '/dashboard/projects/$projectId/tickets/$ticketId': typeof appDashboardProjectsProjectIdTicketsTicketIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)/dashboard': typeof appDashboardRouteWithChildren
  '/(auth)/signup': typeof authSignupRoute
  '/(auth)/': typeof authIndexRoute
  '/(app)/dashboard/companies/': typeof appDashboardCompaniesIndexRoute
  '/(app)/dashboard/home/': typeof appDashboardHomeIndexRoute
  '/(app)/dashboard/$companyId/projects/': typeof appDashboardCompanyIdProjectsIndexRoute
  '/(app)/dashboard/projects/$projectId/': typeof appDashboardProjectsProjectIdIndexRoute
  '/(app)/dashboard/projects/$projectId/tickets/': typeof appDashboardProjectsProjectIdTicketsIndexRoute
  '/(app)/dashboard/projects/$projectId/stories/$storyId/': typeof appDashboardProjectsProjectIdStoriesStoryIdIndexRoute
  '/(app)/dashboard/projects/$projectId/tickets/$ticketId/': typeof appDashboardProjectsProjectIdTicketsTicketIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/signup'
    | '/'
    | '/dashboard/companies'
    | '/dashboard/home'
    | '/dashboard/$companyId/projects'
    | '/dashboard/projects/$projectId'
    | '/dashboard/projects/$projectId/tickets'
    | '/dashboard/projects/$projectId/stories/$storyId'
    | '/dashboard/projects/$projectId/tickets/$ticketId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/signup'
    | '/'
    | '/dashboard/companies'
    | '/dashboard/home'
    | '/dashboard/$companyId/projects'
    | '/dashboard/projects/$projectId'
    | '/dashboard/projects/$projectId/tickets'
    | '/dashboard/projects/$projectId/stories/$storyId'
    | '/dashboard/projects/$projectId/tickets/$ticketId'
  id:
    | '__root__'
    | '/(app)/dashboard'
    | '/(auth)/signup'
    | '/(auth)/'
    | '/(app)/dashboard/companies/'
    | '/(app)/dashboard/home/'
    | '/(app)/dashboard/$companyId/projects/'
    | '/(app)/dashboard/projects/$projectId/'
    | '/(app)/dashboard/projects/$projectId/tickets/'
    | '/(app)/dashboard/projects/$projectId/stories/$storyId/'
    | '/(app)/dashboard/projects/$projectId/tickets/$ticketId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appDashboardRoute: typeof appDashboardRouteWithChildren
  authSignupRoute: typeof authSignupRoute
  authIndexRoute: typeof authIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)/': {
      id: '/(auth)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/dashboard': {
      id: '/(app)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/dashboard/home/': {
      id: '/(app)/dashboard/home/'
      path: '/home'
      fullPath: '/dashboard/home'
      preLoaderRoute: typeof appDashboardHomeIndexRouteImport
      parentRoute: typeof appDashboardRoute
    }
    '/(app)/dashboard/companies/': {
      id: '/(app)/dashboard/companies/'
      path: '/companies'
      fullPath: '/dashboard/companies'
      preLoaderRoute: typeof appDashboardCompaniesIndexRouteImport
      parentRoute: typeof appDashboardRoute
    }
    '/(app)/dashboard/projects/$projectId/': {
      id: '/(app)/dashboard/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/dashboard/projects/$projectId'
      preLoaderRoute: typeof appDashboardProjectsProjectIdIndexRouteImport
      parentRoute: typeof appDashboardRoute
    }
    '/(app)/dashboard/$companyId/projects/': {
      id: '/(app)/dashboard/$companyId/projects/'
      path: '/$companyId/projects'
      fullPath: '/dashboard/$companyId/projects'
      preLoaderRoute: typeof appDashboardCompanyIdProjectsIndexRouteImport
      parentRoute: typeof appDashboardRoute
    }
    '/(app)/dashboard/projects/$projectId/tickets/': {
      id: '/(app)/dashboard/projects/$projectId/tickets/'
      path: '/projects/$projectId/tickets'
      fullPath: '/dashboard/projects/$projectId/tickets'
      preLoaderRoute: typeof appDashboardProjectsProjectIdTicketsIndexRouteImport
      parentRoute: typeof appDashboardRoute
    }
    '/(app)/dashboard/projects/$projectId/tickets/$ticketId/': {
      id: '/(app)/dashboard/projects/$projectId/tickets/$ticketId/'
      path: '/projects/$projectId/tickets/$ticketId'
      fullPath: '/dashboard/projects/$projectId/tickets/$ticketId'
      preLoaderRoute: typeof appDashboardProjectsProjectIdTicketsTicketIdIndexRouteImport
      parentRoute: typeof appDashboardRoute
    }
    '/(app)/dashboard/projects/$projectId/stories/$storyId/': {
      id: '/(app)/dashboard/projects/$projectId/stories/$storyId/'
      path: '/projects/$projectId/stories/$storyId'
      fullPath: '/dashboard/projects/$projectId/stories/$storyId'
      preLoaderRoute: typeof appDashboardProjectsProjectIdStoriesStoryIdIndexRouteImport
      parentRoute: typeof appDashboardRoute
    }
  }
}

interface appDashboardRouteChildren {
  appDashboardCompaniesIndexRoute: typeof appDashboardCompaniesIndexRoute
  appDashboardHomeIndexRoute: typeof appDashboardHomeIndexRoute
  appDashboardCompanyIdProjectsIndexRoute: typeof appDashboardCompanyIdProjectsIndexRoute
  appDashboardProjectsProjectIdIndexRoute: typeof appDashboardProjectsProjectIdIndexRoute
  appDashboardProjectsProjectIdTicketsIndexRoute: typeof appDashboardProjectsProjectIdTicketsIndexRoute
  appDashboardProjectsProjectIdStoriesStoryIdIndexRoute: typeof appDashboardProjectsProjectIdStoriesStoryIdIndexRoute
  appDashboardProjectsProjectIdTicketsTicketIdIndexRoute: typeof appDashboardProjectsProjectIdTicketsTicketIdIndexRoute
}

const appDashboardRouteChildren: appDashboardRouteChildren = {
  appDashboardCompaniesIndexRoute: appDashboardCompaniesIndexRoute,
  appDashboardHomeIndexRoute: appDashboardHomeIndexRoute,
  appDashboardCompanyIdProjectsIndexRoute:
    appDashboardCompanyIdProjectsIndexRoute,
  appDashboardProjectsProjectIdIndexRoute:
    appDashboardProjectsProjectIdIndexRoute,
  appDashboardProjectsProjectIdTicketsIndexRoute:
    appDashboardProjectsProjectIdTicketsIndexRoute,
  appDashboardProjectsProjectIdStoriesStoryIdIndexRoute:
    appDashboardProjectsProjectIdStoriesStoryIdIndexRoute,
  appDashboardProjectsProjectIdTicketsTicketIdIndexRoute:
    appDashboardProjectsProjectIdTicketsTicketIdIndexRoute,
}

const appDashboardRouteWithChildren = appDashboardRoute._addFileChildren(
  appDashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appDashboardRoute: appDashboardRouteWithChildren,
  authSignupRoute: authSignupRoute,
  authIndexRoute: authIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
