/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authIndexRouteImport } from './routes/(auth)/index'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as appDashboardIndexRouteImport } from './routes/(app)/dashboard/index'
import { Route as appDashboardCompaniesIndexRouteImport } from './routes/(app)/dashboard/companies/index'
import { Route as appDashboardProjectsAllIndexRouteImport } from './routes/(app)/dashboard/projects/all/index'
import { Route as appDashboardCompanyCompanyIdProjectsAllIndexRouteImport } from './routes/(app)/dashboard/company/$companyId/projects/all/index'
import { Route as appDashboardCompanyCompanyIdProjectsProjectIdIndexRouteImport } from './routes/(app)/dashboard/company/$companyId/projects/$projectId/index'
import { Route as appDashboardCompanyCompanyIdProjectsProjectIdStoriesIndexRouteImport } from './routes/(app)/dashboard/company/$companyId/projects/$projectId/stories/index'
import { Route as appDashboardCompanyCompanyIdProjectsProjectIdStoriesTicketsIndexRouteImport } from './routes/(app)/dashboard/company/$companyId/projects/$projectId/stories/tickets/index'
import { Route as appDashboardCompanyCompanyIdProjectsProjectIdStoriesTicketsTicketIdIndexRouteImport } from './routes/(app)/dashboard/company/$companyId/projects/$projectId/stories/tickets/$ticketId/index'

const authIndexRoute = authIndexRouteImport.update({
  id: '/(auth)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const appDashboardIndexRoute = appDashboardIndexRouteImport.update({
  id: '/(app)/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const appDashboardCompaniesIndexRoute =
  appDashboardCompaniesIndexRouteImport.update({
    id: '/(app)/dashboard/companies/',
    path: '/dashboard/companies/',
    getParentRoute: () => rootRouteImport,
  } as any)
const appDashboardProjectsAllIndexRoute =
  appDashboardProjectsAllIndexRouteImport.update({
    id: '/(app)/dashboard/projects/all/',
    path: '/dashboard/projects/all/',
    getParentRoute: () => rootRouteImport,
  } as any)
const appDashboardCompanyCompanyIdProjectsAllIndexRoute =
  appDashboardCompanyCompanyIdProjectsAllIndexRouteImport.update({
    id: '/(app)/dashboard/company/$companyId/projects/all/',
    path: '/dashboard/company/$companyId/projects/all/',
    getParentRoute: () => rootRouteImport,
  } as any)
const appDashboardCompanyCompanyIdProjectsProjectIdIndexRoute =
  appDashboardCompanyCompanyIdProjectsProjectIdIndexRouteImport.update({
    id: '/(app)/dashboard/company/$companyId/projects/$projectId/',
    path: '/dashboard/company/$companyId/projects/$projectId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const appDashboardCompanyCompanyIdProjectsProjectIdStoriesIndexRoute =
  appDashboardCompanyCompanyIdProjectsProjectIdStoriesIndexRouteImport.update({
    id: '/(app)/dashboard/company/$companyId/projects/$projectId/stories/',
    path: '/dashboard/company/$companyId/projects/$projectId/stories/',
    getParentRoute: () => rootRouteImport,
  } as any)
const appDashboardCompanyCompanyIdProjectsProjectIdStoriesTicketsIndexRoute =
  appDashboardCompanyCompanyIdProjectsProjectIdStoriesTicketsIndexRouteImport.update(
    {
      id: '/(app)/dashboard/company/$companyId/projects/$projectId/stories/tickets/',
      path: '/dashboard/company/$companyId/projects/$projectId/stories/tickets/',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const appDashboardCompanyCompanyIdProjectsProjectIdStoriesTicketsTicketIdIndexRoute =
  appDashboardCompanyCompanyIdProjectsProjectIdStoriesTicketsTicketIdIndexRouteImport.update(
    {
      id: '/(app)/dashboard/company/$companyId/projects/$projectId/stories/tickets/$ticketId/',
      path: '/dashboard/company/$companyId/projects/$projectId/stories/tickets/$ticketId/',
      getParentRoute: () => rootRouteImport,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/signup': typeof authSignupRoute
  '/': typeof authIndexRoute
  '/dashboard': typeof appDashboardIndexRoute
  '/dashboard/companies': typeof appDashboardCompaniesIndexRoute
  '/dashboard/projects/all': typeof appDashboardProjectsAllIndexRoute
  '/dashboard/company/$companyId/projects/$projectId': typeof appDashboardCompanyCompanyIdProjectsProjectIdIndexRoute
  '/dashboard/company/$companyId/projects/all': typeof appDashboardCompanyCompanyIdProjectsAllIndexRoute
  '/dashboard/company/$companyId/projects/$projectId/stories': typeof appDashboardCompanyCompanyIdProjectsProjectIdStoriesIndexRoute
  '/dashboard/company/$companyId/projects/$projectId/stories/tickets': typeof appDashboardCompanyCompanyIdProjectsProjectIdStoriesTicketsIndexRoute
  '/dashboard/company/$companyId/projects/$projectId/stories/tickets/$ticketId': typeof appDashboardCompanyCompanyIdProjectsProjectIdStoriesTicketsTicketIdIndexRoute
}
export interface FileRoutesByTo {
  '/signup': typeof authSignupRoute
  '/': typeof authIndexRoute
  '/dashboard': typeof appDashboardIndexRoute
  '/dashboard/companies': typeof appDashboardCompaniesIndexRoute
  '/dashboard/projects/all': typeof appDashboardProjectsAllIndexRoute
  '/dashboard/company/$companyId/projects/$projectId': typeof appDashboardCompanyCompanyIdProjectsProjectIdIndexRoute
  '/dashboard/company/$companyId/projects/all': typeof appDashboardCompanyCompanyIdProjectsAllIndexRoute
  '/dashboard/company/$companyId/projects/$projectId/stories': typeof appDashboardCompanyCompanyIdProjectsProjectIdStoriesIndexRoute
  '/dashboard/company/$companyId/projects/$projectId/stories/tickets': typeof appDashboardCompanyCompanyIdProjectsProjectIdStoriesTicketsIndexRoute
  '/dashboard/company/$companyId/projects/$projectId/stories/tickets/$ticketId': typeof appDashboardCompanyCompanyIdProjectsProjectIdStoriesTicketsTicketIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)/signup': typeof authSignupRoute
  '/(auth)/': typeof authIndexRoute
  '/(app)/dashboard/': typeof appDashboardIndexRoute
  '/(app)/dashboard/companies/': typeof appDashboardCompaniesIndexRoute
  '/(app)/dashboard/projects/all/': typeof appDashboardProjectsAllIndexRoute
  '/(app)/dashboard/company/$companyId/projects/$projectId/': typeof appDashboardCompanyCompanyIdProjectsProjectIdIndexRoute
  '/(app)/dashboard/company/$companyId/projects/all/': typeof appDashboardCompanyCompanyIdProjectsAllIndexRoute
  '/(app)/dashboard/company/$companyId/projects/$projectId/stories/': typeof appDashboardCompanyCompanyIdProjectsProjectIdStoriesIndexRoute
  '/(app)/dashboard/company/$companyId/projects/$projectId/stories/tickets/': typeof appDashboardCompanyCompanyIdProjectsProjectIdStoriesTicketsIndexRoute
  '/(app)/dashboard/company/$companyId/projects/$projectId/stories/tickets/$ticketId/': typeof appDashboardCompanyCompanyIdProjectsProjectIdStoriesTicketsTicketIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/signup'
    | '/'
    | '/dashboard'
    | '/dashboard/companies'
    | '/dashboard/projects/all'
    | '/dashboard/company/$companyId/projects/$projectId'
    | '/dashboard/company/$companyId/projects/all'
    | '/dashboard/company/$companyId/projects/$projectId/stories'
    | '/dashboard/company/$companyId/projects/$projectId/stories/tickets'
    | '/dashboard/company/$companyId/projects/$projectId/stories/tickets/$ticketId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/signup'
    | '/'
    | '/dashboard'
    | '/dashboard/companies'
    | '/dashboard/projects/all'
    | '/dashboard/company/$companyId/projects/$projectId'
    | '/dashboard/company/$companyId/projects/all'
    | '/dashboard/company/$companyId/projects/$projectId/stories'
    | '/dashboard/company/$companyId/projects/$projectId/stories/tickets'
    | '/dashboard/company/$companyId/projects/$projectId/stories/tickets/$ticketId'
  id:
    | '__root__'
    | '/(auth)/signup'
    | '/(auth)/'
    | '/(app)/dashboard/'
    | '/(app)/dashboard/companies/'
    | '/(app)/dashboard/projects/all/'
    | '/(app)/dashboard/company/$companyId/projects/$projectId/'
    | '/(app)/dashboard/company/$companyId/projects/all/'
    | '/(app)/dashboard/company/$companyId/projects/$projectId/stories/'
    | '/(app)/dashboard/company/$companyId/projects/$projectId/stories/tickets/'
    | '/(app)/dashboard/company/$companyId/projects/$projectId/stories/tickets/$ticketId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authSignupRoute: typeof authSignupRoute
  authIndexRoute: typeof authIndexRoute
  appDashboardIndexRoute: typeof appDashboardIndexRoute
  appDashboardCompaniesIndexRoute: typeof appDashboardCompaniesIndexRoute
  appDashboardProjectsAllIndexRoute: typeof appDashboardProjectsAllIndexRoute
  appDashboardCompanyCompanyIdProjectsProjectIdIndexRoute: typeof appDashboardCompanyCompanyIdProjectsProjectIdIndexRoute
  appDashboardCompanyCompanyIdProjectsAllIndexRoute: typeof appDashboardCompanyCompanyIdProjectsAllIndexRoute
  appDashboardCompanyCompanyIdProjectsProjectIdStoriesIndexRoute: typeof appDashboardCompanyCompanyIdProjectsProjectIdStoriesIndexRoute
  appDashboardCompanyCompanyIdProjectsProjectIdStoriesTicketsIndexRoute: typeof appDashboardCompanyCompanyIdProjectsProjectIdStoriesTicketsIndexRoute
  appDashboardCompanyCompanyIdProjectsProjectIdStoriesTicketsTicketIdIndexRoute: typeof appDashboardCompanyCompanyIdProjectsProjectIdStoriesTicketsTicketIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)/': {
      id: '/(auth)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/dashboard/': {
      id: '/(app)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/dashboard/companies/': {
      id: '/(app)/dashboard/companies/'
      path: '/dashboard/companies'
      fullPath: '/dashboard/companies'
      preLoaderRoute: typeof appDashboardCompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/dashboard/projects/all/': {
      id: '/(app)/dashboard/projects/all/'
      path: '/dashboard/projects/all'
      fullPath: '/dashboard/projects/all'
      preLoaderRoute: typeof appDashboardProjectsAllIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/dashboard/company/$companyId/projects/all/': {
      id: '/(app)/dashboard/company/$companyId/projects/all/'
      path: '/dashboard/company/$companyId/projects/all'
      fullPath: '/dashboard/company/$companyId/projects/all'
      preLoaderRoute: typeof appDashboardCompanyCompanyIdProjectsAllIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/dashboard/company/$companyId/projects/$projectId/': {
      id: '/(app)/dashboard/company/$companyId/projects/$projectId/'
      path: '/dashboard/company/$companyId/projects/$projectId'
      fullPath: '/dashboard/company/$companyId/projects/$projectId'
      preLoaderRoute: typeof appDashboardCompanyCompanyIdProjectsProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/dashboard/company/$companyId/projects/$projectId/stories/': {
      id: '/(app)/dashboard/company/$companyId/projects/$projectId/stories/'
      path: '/dashboard/company/$companyId/projects/$projectId/stories'
      fullPath: '/dashboard/company/$companyId/projects/$projectId/stories'
      preLoaderRoute: typeof appDashboardCompanyCompanyIdProjectsProjectIdStoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/dashboard/company/$companyId/projects/$projectId/stories/tickets/': {
      id: '/(app)/dashboard/company/$companyId/projects/$projectId/stories/tickets/'
      path: '/dashboard/company/$companyId/projects/$projectId/stories/tickets'
      fullPath: '/dashboard/company/$companyId/projects/$projectId/stories/tickets'
      preLoaderRoute: typeof appDashboardCompanyCompanyIdProjectsProjectIdStoriesTicketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/dashboard/company/$companyId/projects/$projectId/stories/tickets/$ticketId/': {
      id: '/(app)/dashboard/company/$companyId/projects/$projectId/stories/tickets/$ticketId/'
      path: '/dashboard/company/$companyId/projects/$projectId/stories/tickets/$ticketId'
      fullPath: '/dashboard/company/$companyId/projects/$projectId/stories/tickets/$ticketId'
      preLoaderRoute: typeof appDashboardCompanyCompanyIdProjectsProjectIdStoriesTicketsTicketIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  authSignupRoute: authSignupRoute,
  authIndexRoute: authIndexRoute,
  appDashboardIndexRoute: appDashboardIndexRoute,
  appDashboardCompaniesIndexRoute: appDashboardCompaniesIndexRoute,
  appDashboardProjectsAllIndexRoute: appDashboardProjectsAllIndexRoute,
  appDashboardCompanyCompanyIdProjectsProjectIdIndexRoute:
    appDashboardCompanyCompanyIdProjectsProjectIdIndexRoute,
  appDashboardCompanyCompanyIdProjectsAllIndexRoute:
    appDashboardCompanyCompanyIdProjectsAllIndexRoute,
  appDashboardCompanyCompanyIdProjectsProjectIdStoriesIndexRoute:
    appDashboardCompanyCompanyIdProjectsProjectIdStoriesIndexRoute,
  appDashboardCompanyCompanyIdProjectsProjectIdStoriesTicketsIndexRoute:
    appDashboardCompanyCompanyIdProjectsProjectIdStoriesTicketsIndexRoute,
  appDashboardCompanyCompanyIdProjectsProjectIdStoriesTicketsTicketIdIndexRoute:
    appDashboardCompanyCompanyIdProjectsProjectIdStoriesTicketsTicketIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
