/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authIndexRouteImport } from './routes/(auth)/index'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as appDashboardRouteImport } from './routes/(app)/dashboard'
import { Route as appDashboardHomeIndexRouteImport } from './routes/(app)/dashboard/home/index'
import { Route as appDashboardCompaniesIndexRouteImport } from './routes/(app)/dashboard/companies/index'
import { Route as appDashboardProjectIdIndexRouteImport } from './routes/(app)/dashboard/$projectId/index'
import { Route as appDashboardProjectsAllIndexRouteImport } from './routes/(app)/dashboard/projects/all/index'
import { Route as appDashboardCompanyIdProjectsAllIndexRouteImport } from './routes/(app)/dashboard/$companyId/projects/all/index'
import { Route as appDashboardCompanyIdProjectsProjectIdIndexRouteImport } from './routes/(app)/dashboard/$companyId/projects/$projectId/index'
import { Route as appDashboardCompanyIdProjectsProjectIdStoriesIndexRouteImport } from './routes/(app)/dashboard/$companyId/projects/$projectId/stories/index'
import { Route as appDashboardCompanyIdProjectsProjectIdStoriesTicketsIndexRouteImport } from './routes/(app)/dashboard/$companyId/projects/$projectId/stories/tickets/index'
import { Route as appDashboardCompanyIdProjectsProjectIdStoriesTicketsTicketIdIndexRouteImport } from './routes/(app)/dashboard/$companyId/projects/$projectId/stories/tickets/$ticketId/index'

const authIndexRoute = authIndexRouteImport.update({
  id: '/(auth)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const appDashboardRoute = appDashboardRouteImport.update({
  id: '/(app)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const appDashboardHomeIndexRoute = appDashboardHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => appDashboardRoute,
} as any)
const appDashboardCompaniesIndexRoute =
  appDashboardCompaniesIndexRouteImport.update({
    id: '/companies/',
    path: '/companies/',
    getParentRoute: () => appDashboardRoute,
  } as any)
const appDashboardProjectIdIndexRoute =
  appDashboardProjectIdIndexRouteImport.update({
    id: '/$projectId/',
    path: '/$projectId/',
    getParentRoute: () => appDashboardRoute,
  } as any)
const appDashboardProjectsAllIndexRoute =
  appDashboardProjectsAllIndexRouteImport.update({
    id: '/projects/all/',
    path: '/projects/all/',
    getParentRoute: () => appDashboardRoute,
  } as any)
const appDashboardCompanyIdProjectsAllIndexRoute =
  appDashboardCompanyIdProjectsAllIndexRouteImport.update({
    id: '/$companyId/projects/all/',
    path: '/$companyId/projects/all/',
    getParentRoute: () => appDashboardRoute,
  } as any)
const appDashboardCompanyIdProjectsProjectIdIndexRoute =
  appDashboardCompanyIdProjectsProjectIdIndexRouteImport.update({
    id: '/$companyId/projects/$projectId/',
    path: '/$companyId/projects/$projectId/',
    getParentRoute: () => appDashboardRoute,
  } as any)
const appDashboardCompanyIdProjectsProjectIdStoriesIndexRoute =
  appDashboardCompanyIdProjectsProjectIdStoriesIndexRouteImport.update({
    id: '/$companyId/projects/$projectId/stories/',
    path: '/$companyId/projects/$projectId/stories/',
    getParentRoute: () => appDashboardRoute,
  } as any)
const appDashboardCompanyIdProjectsProjectIdStoriesTicketsIndexRoute =
  appDashboardCompanyIdProjectsProjectIdStoriesTicketsIndexRouteImport.update({
    id: '/$companyId/projects/$projectId/stories/tickets/',
    path: '/$companyId/projects/$projectId/stories/tickets/',
    getParentRoute: () => appDashboardRoute,
  } as any)
const appDashboardCompanyIdProjectsProjectIdStoriesTicketsTicketIdIndexRoute =
  appDashboardCompanyIdProjectsProjectIdStoriesTicketsTicketIdIndexRouteImport.update(
    {
      id: '/$companyId/projects/$projectId/stories/tickets/$ticketId/',
      path: '/$companyId/projects/$projectId/stories/tickets/$ticketId/',
      getParentRoute: () => appDashboardRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/dashboard': typeof appDashboardRouteWithChildren
  '/signup': typeof authSignupRoute
  '/': typeof authIndexRoute
  '/dashboard/$projectId': typeof appDashboardProjectIdIndexRoute
  '/dashboard/companies': typeof appDashboardCompaniesIndexRoute
  '/dashboard/home': typeof appDashboardHomeIndexRoute
  '/dashboard/projects/all': typeof appDashboardProjectsAllIndexRoute
  '/dashboard/$companyId/projects/$projectId': typeof appDashboardCompanyIdProjectsProjectIdIndexRoute
  '/dashboard/$companyId/projects/all': typeof appDashboardCompanyIdProjectsAllIndexRoute
  '/dashboard/$companyId/projects/$projectId/stories': typeof appDashboardCompanyIdProjectsProjectIdStoriesIndexRoute
  '/dashboard/$companyId/projects/$projectId/stories/tickets': typeof appDashboardCompanyIdProjectsProjectIdStoriesTicketsIndexRoute
  '/dashboard/$companyId/projects/$projectId/stories/tickets/$ticketId': typeof appDashboardCompanyIdProjectsProjectIdStoriesTicketsTicketIdIndexRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof appDashboardRouteWithChildren
  '/signup': typeof authSignupRoute
  '/': typeof authIndexRoute
  '/dashboard/$projectId': typeof appDashboardProjectIdIndexRoute
  '/dashboard/companies': typeof appDashboardCompaniesIndexRoute
  '/dashboard/home': typeof appDashboardHomeIndexRoute
  '/dashboard/projects/all': typeof appDashboardProjectsAllIndexRoute
  '/dashboard/$companyId/projects/$projectId': typeof appDashboardCompanyIdProjectsProjectIdIndexRoute
  '/dashboard/$companyId/projects/all': typeof appDashboardCompanyIdProjectsAllIndexRoute
  '/dashboard/$companyId/projects/$projectId/stories': typeof appDashboardCompanyIdProjectsProjectIdStoriesIndexRoute
  '/dashboard/$companyId/projects/$projectId/stories/tickets': typeof appDashboardCompanyIdProjectsProjectIdStoriesTicketsIndexRoute
  '/dashboard/$companyId/projects/$projectId/stories/tickets/$ticketId': typeof appDashboardCompanyIdProjectsProjectIdStoriesTicketsTicketIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)/dashboard': typeof appDashboardRouteWithChildren
  '/(auth)/signup': typeof authSignupRoute
  '/(auth)/': typeof authIndexRoute
  '/(app)/dashboard/$projectId/': typeof appDashboardProjectIdIndexRoute
  '/(app)/dashboard/companies/': typeof appDashboardCompaniesIndexRoute
  '/(app)/dashboard/home/': typeof appDashboardHomeIndexRoute
  '/(app)/dashboard/projects/all/': typeof appDashboardProjectsAllIndexRoute
  '/(app)/dashboard/$companyId/projects/$projectId/': typeof appDashboardCompanyIdProjectsProjectIdIndexRoute
  '/(app)/dashboard/$companyId/projects/all/': typeof appDashboardCompanyIdProjectsAllIndexRoute
  '/(app)/dashboard/$companyId/projects/$projectId/stories/': typeof appDashboardCompanyIdProjectsProjectIdStoriesIndexRoute
  '/(app)/dashboard/$companyId/projects/$projectId/stories/tickets/': typeof appDashboardCompanyIdProjectsProjectIdStoriesTicketsIndexRoute
  '/(app)/dashboard/$companyId/projects/$projectId/stories/tickets/$ticketId/': typeof appDashboardCompanyIdProjectsProjectIdStoriesTicketsTicketIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/signup'
    | '/'
    | '/dashboard/$projectId'
    | '/dashboard/companies'
    | '/dashboard/home'
    | '/dashboard/projects/all'
    | '/dashboard/$companyId/projects/$projectId'
    | '/dashboard/$companyId/projects/all'
    | '/dashboard/$companyId/projects/$projectId/stories'
    | '/dashboard/$companyId/projects/$projectId/stories/tickets'
    | '/dashboard/$companyId/projects/$projectId/stories/tickets/$ticketId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/signup'
    | '/'
    | '/dashboard/$projectId'
    | '/dashboard/companies'
    | '/dashboard/home'
    | '/dashboard/projects/all'
    | '/dashboard/$companyId/projects/$projectId'
    | '/dashboard/$companyId/projects/all'
    | '/dashboard/$companyId/projects/$projectId/stories'
    | '/dashboard/$companyId/projects/$projectId/stories/tickets'
    | '/dashboard/$companyId/projects/$projectId/stories/tickets/$ticketId'
  id:
    | '__root__'
    | '/(app)/dashboard'
    | '/(auth)/signup'
    | '/(auth)/'
    | '/(app)/dashboard/$projectId/'
    | '/(app)/dashboard/companies/'
    | '/(app)/dashboard/home/'
    | '/(app)/dashboard/projects/all/'
    | '/(app)/dashboard/$companyId/projects/$projectId/'
    | '/(app)/dashboard/$companyId/projects/all/'
    | '/(app)/dashboard/$companyId/projects/$projectId/stories/'
    | '/(app)/dashboard/$companyId/projects/$projectId/stories/tickets/'
    | '/(app)/dashboard/$companyId/projects/$projectId/stories/tickets/$ticketId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appDashboardRoute: typeof appDashboardRouteWithChildren
  authSignupRoute: typeof authSignupRoute
  authIndexRoute: typeof authIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)/': {
      id: '/(auth)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/dashboard': {
      id: '/(app)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/dashboard/home/': {
      id: '/(app)/dashboard/home/'
      path: '/home'
      fullPath: '/dashboard/home'
      preLoaderRoute: typeof appDashboardHomeIndexRouteImport
      parentRoute: typeof appDashboardRoute
    }
    '/(app)/dashboard/companies/': {
      id: '/(app)/dashboard/companies/'
      path: '/companies'
      fullPath: '/dashboard/companies'
      preLoaderRoute: typeof appDashboardCompaniesIndexRouteImport
      parentRoute: typeof appDashboardRoute
    }
    '/(app)/dashboard/$projectId/': {
      id: '/(app)/dashboard/$projectId/'
      path: '/$projectId'
      fullPath: '/dashboard/$projectId'
      preLoaderRoute: typeof appDashboardProjectIdIndexRouteImport
      parentRoute: typeof appDashboardRoute
    }
    '/(app)/dashboard/projects/all/': {
      id: '/(app)/dashboard/projects/all/'
      path: '/projects/all'
      fullPath: '/dashboard/projects/all'
      preLoaderRoute: typeof appDashboardProjectsAllIndexRouteImport
      parentRoute: typeof appDashboardRoute
    }
    '/(app)/dashboard/$companyId/projects/all/': {
      id: '/(app)/dashboard/$companyId/projects/all/'
      path: '/$companyId/projects/all'
      fullPath: '/dashboard/$companyId/projects/all'
      preLoaderRoute: typeof appDashboardCompanyIdProjectsAllIndexRouteImport
      parentRoute: typeof appDashboardRoute
    }
    '/(app)/dashboard/$companyId/projects/$projectId/': {
      id: '/(app)/dashboard/$companyId/projects/$projectId/'
      path: '/$companyId/projects/$projectId'
      fullPath: '/dashboard/$companyId/projects/$projectId'
      preLoaderRoute: typeof appDashboardCompanyIdProjectsProjectIdIndexRouteImport
      parentRoute: typeof appDashboardRoute
    }
    '/(app)/dashboard/$companyId/projects/$projectId/stories/': {
      id: '/(app)/dashboard/$companyId/projects/$projectId/stories/'
      path: '/$companyId/projects/$projectId/stories'
      fullPath: '/dashboard/$companyId/projects/$projectId/stories'
      preLoaderRoute: typeof appDashboardCompanyIdProjectsProjectIdStoriesIndexRouteImport
      parentRoute: typeof appDashboardRoute
    }
    '/(app)/dashboard/$companyId/projects/$projectId/stories/tickets/': {
      id: '/(app)/dashboard/$companyId/projects/$projectId/stories/tickets/'
      path: '/$companyId/projects/$projectId/stories/tickets'
      fullPath: '/dashboard/$companyId/projects/$projectId/stories/tickets'
      preLoaderRoute: typeof appDashboardCompanyIdProjectsProjectIdStoriesTicketsIndexRouteImport
      parentRoute: typeof appDashboardRoute
    }
    '/(app)/dashboard/$companyId/projects/$projectId/stories/tickets/$ticketId/': {
      id: '/(app)/dashboard/$companyId/projects/$projectId/stories/tickets/$ticketId/'
      path: '/$companyId/projects/$projectId/stories/tickets/$ticketId'
      fullPath: '/dashboard/$companyId/projects/$projectId/stories/tickets/$ticketId'
      preLoaderRoute: typeof appDashboardCompanyIdProjectsProjectIdStoriesTicketsTicketIdIndexRouteImport
      parentRoute: typeof appDashboardRoute
    }
  }
}

interface appDashboardRouteChildren {
  appDashboardProjectIdIndexRoute: typeof appDashboardProjectIdIndexRoute
  appDashboardCompaniesIndexRoute: typeof appDashboardCompaniesIndexRoute
  appDashboardHomeIndexRoute: typeof appDashboardHomeIndexRoute
  appDashboardProjectsAllIndexRoute: typeof appDashboardProjectsAllIndexRoute
  appDashboardCompanyIdProjectsProjectIdIndexRoute: typeof appDashboardCompanyIdProjectsProjectIdIndexRoute
  appDashboardCompanyIdProjectsAllIndexRoute: typeof appDashboardCompanyIdProjectsAllIndexRoute
  appDashboardCompanyIdProjectsProjectIdStoriesIndexRoute: typeof appDashboardCompanyIdProjectsProjectIdStoriesIndexRoute
  appDashboardCompanyIdProjectsProjectIdStoriesTicketsIndexRoute: typeof appDashboardCompanyIdProjectsProjectIdStoriesTicketsIndexRoute
  appDashboardCompanyIdProjectsProjectIdStoriesTicketsTicketIdIndexRoute: typeof appDashboardCompanyIdProjectsProjectIdStoriesTicketsTicketIdIndexRoute
}

const appDashboardRouteChildren: appDashboardRouteChildren = {
  appDashboardProjectIdIndexRoute: appDashboardProjectIdIndexRoute,
  appDashboardCompaniesIndexRoute: appDashboardCompaniesIndexRoute,
  appDashboardHomeIndexRoute: appDashboardHomeIndexRoute,
  appDashboardProjectsAllIndexRoute: appDashboardProjectsAllIndexRoute,
  appDashboardCompanyIdProjectsProjectIdIndexRoute:
    appDashboardCompanyIdProjectsProjectIdIndexRoute,
  appDashboardCompanyIdProjectsAllIndexRoute:
    appDashboardCompanyIdProjectsAllIndexRoute,
  appDashboardCompanyIdProjectsProjectIdStoriesIndexRoute:
    appDashboardCompanyIdProjectsProjectIdStoriesIndexRoute,
  appDashboardCompanyIdProjectsProjectIdStoriesTicketsIndexRoute:
    appDashboardCompanyIdProjectsProjectIdStoriesTicketsIndexRoute,
  appDashboardCompanyIdProjectsProjectIdStoriesTicketsTicketIdIndexRoute:
    appDashboardCompanyIdProjectsProjectIdStoriesTicketsTicketIdIndexRoute,
}

const appDashboardRouteWithChildren = appDashboardRoute._addFileChildren(
  appDashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appDashboardRoute: appDashboardRouteWithChildren,
  authSignupRoute: authSignupRoute,
  authIndexRoute: authIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
